- name: "rc1 to get information"
  hosts: R2
  connection: local

  tasks:
    - name: "set ospf config on R2"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        url_username: user
        url_password: pass
        method: PUT
        headers:
          Accept: 
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: "application/yang-data+json"
        body_format: json
        body: "{{ OSPF_Conf }}"      
        validate_certs: false
        status_code:
          - 200
          - 204

