---

- name: Check gathering facts
  hosts: Cisco_N
  gather_facts: false
  connection: network_cli



  tasks:
    - name: Gather IOS facts
      ios_facts:
        gather_subset: interfaces  # Specify that you want to gather interface information
    - name: facts gathering
      debug:
        msg: "{{ ansible_facts }}"
 
        